# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Expressly Developer Portal
email: info@buyexpressly.com
description: > # this means to ignore newlines until "baseurl:"
  The Expressly Network D=developer hub. Your one stop shop for
  SDK and ecommerce plug-ins and module to integrate your business
  into the Expressly Network.
baseurl: ""
url: "http://developer.buyexpressly.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
